name: validation_notifier
description: A ValueNotifier that validates a value against a collection of customizable rules.
version: 1.0.0+1
author: Dustin Catap
homepage: https://github.com/cross-solutions/flutter-validation-notifier
repository: https://github.com/cross-solutions/flutter-validation-notifier

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
