name: validation_notifier
description: A ValueNotifier that validates a value against a collection of customizable rules.
version: 1.4.0
homepage: https://github.com/cross-solutions/flutter-validation-notifier
repository: https://github.com/cross-solutions/flutter-validation-notifier

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
